# Generated by Django 5.0.4 on 2024-04-28 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
        ('auther', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='auther',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auther.author'),
            preserve_default=False,
        ),
    ]
