# Generated by Django 5.0.4 on 2024-04-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
    ]
